mylist1=['a',10,7.2,'Jhon']
print(mylist1)
mylist2=['Pythone',20]
mylist1+=mylist2
print(mylist1)
print(mylist2*2)
print(mylist1[1:5])
mylist2.append("10")
print(mylist2)
l=['c','d']
mylist2.extend(l)
print(mylist2)
l.remove("d")
print(l)
print(len(mylist1))
str1="lists in python"
l=list(str1)
print(l)
print(l.pop())
print(l.count("s"))
print(l.index("p"))